name: ArtDiversions
highlighter: rouge
baseurl:

paginate_path: "/page:num"
paginate: 4
permalink: /:title/
excerpt_separator: <!--more-->

collections_dir: collections
collections:
  mechanics:
    output: true
  observers:
    output: true
  questions:
    output: true
  rules:
    output: true
  videos:
    output: true
