name: ArtDiversions
highlighter: rouge
baseurl:

paginate_path: "/page:num"
paginate: 4
permalink: /:title/
excerpt_separator: <!--more-->

collections_dir: collections
collections:
  videos:
    output: true
